version: "2.4"

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx-conf/conf.d:/etc/nginx/conf.d
      - ./nginx-conf/ssl.conf:/etc/nginx/ssl.conf
      - ./certbot/conf:/etc/letsencrypt
#    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  
  testserver:
    image: "test"
    build:
      context: .
      dockerfile: Dockerfile
    